# Generated by Django 5.0.6 on 2024-06-06 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagenC', models.ImageField(upload_to='categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomrbe', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('paginaOficial', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagenP', models.ImageField(upload_to='Productos/')),
                ('modelo_3d', models.FileField(upload_to='modelos')),
                ('cantidad_disponible', models.IntegerField()),
                ('recomendados', models.BooleanField(default=False)),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('largo', models.FloatField()),
                ('paginaComprar', models.URLField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto_app.categoria')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='producto_app.entidad')),
            ],
        ),
    ]
