# Generated by Django 5.0.6 on 2024-06-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='nomrbe',
            new_name='nombre',
        ),
    ]
