# Generated by Django 5.0 on 2023-12-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagenC',
        ),
    ]
