# Generated by Django 5.0.6 on 2024-06-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0002_rename_nomrbe_entidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(default='', upload_to='Entidad/'),
        ),
    ]
