# Generated by Django 5.0 on 2023-12-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0002_remove_categoria_imagenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagenC',
            field=models.ImageField(default='mesa.png', upload_to='categorias/'),
        ),
    ]
