# Generated by Django 5.0 on 2023-12-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0003_categoria_imagenc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagenC',
            field=models.ImageField(upload_to='categorias/'),
        ),
    ]
