# Generated by Django 5.0 on 2023-12-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0004_alter_categoria_imagenc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo_3d',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenP',
            field=models.ImageField(upload_to='Productos/'),
        ),
    ]
