# Generated by Django 5.0 on 2023-12-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0005_remove_producto_modelo_3d_alter_producto_imagenp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
