# Generated by Django 5.0.6 on 2024-06-15 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0005_remove_producto_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo_3d',
            field=models.FileField(upload_to='modelos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb'])]),
        ),
    ]
