# Generated by Django 5.0 on 2023-12-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0006_remove_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
