# Generated by Django 5.0.6 on 2024-06-16 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0006_alter_producto_modelo_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidadM',
            field=models.CharField(default='metros', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo_3d',
            field=models.FileField(upload_to='modelos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])]),
        ),
    ]
