# Generated by Django 5.0 on 2023-12-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0008_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo_3d',
            field=models.FileField(default='media\\Furniture_Office-Desks-Tables_Alias-Design_biplane-round-O90-401-O120-402-O140-403.stl', upload_to='modelos'),
        ),
    ]
