# Generated by Django 5.0.6 on 2024-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0008_alter_producto_unidadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidadM',
            field=models.CharField(choices=[('metro', 'm'), ('pulgada', 'in'), ('centímetro', 'cm')], default='metro', max_length=50),
        ),
    ]
