# Generated by Django 5.0 on 2023-12-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0009_producto_modelo_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
