# Generated by Django 5.0.6 on 2024-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0009_alter_producto_unidadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidadM',
            field=models.CharField(choices=[('in', 'Pulgadas'), ('m', 'Metros'), ('cm', 'Centímetros')], default='m', max_length=2),
        ),
    ]
