# Generated by Django 5.0.6 on 2024-06-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0010_alter_producto_unidadm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='paginaComprar',
        ),
    ]
