# Generated by Django 5.0 on 2023-12-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0011_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto_app.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo_3d',
            field=models.FileField(upload_to='modelos'),
        ),
    ]
