# Generated by Django 5.0 on 2024-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0012_alter_producto_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='recomendados',
            field=models.BooleanField(default=False),
        ),
    ]
