# Generated by Django 5.0 on 2024-01-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0013_producto_recomendados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='cantidad',
        ),
    ]
