# Generated by Django 5.0 on 2024-01-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0016_alter_carrito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='carrito_id',
            field=models.IntegerField(default=0),
        ),
    ]
