# Generated by Django 5.0 on 2024-01-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0017_producto_carrito_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='carrito_id',
        ),
    ]
