# Generated by Django 5.0 on 2024-01-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0018_remove_producto_carrito_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
