# Generated by Django 5.0 on 2024-01-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0019_delete_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='perteneCarrito',
            field=models.BooleanField(default=False),
        ),
    ]
