# Generated by Django 5.0 on 2024-01-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0020_producto_pertenecarrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
