# Generated by Django 5.0 on 2024-02-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0022_remove_pedido_completado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='perteneCarrito',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto_app.producto'),
        ),
    ]
