# Generated by Django 3.2.23 on 2024-02-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0023_remove_carrito_producto_producto_pertenecarrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='perteneCarrito',
        ),
    ]
