# Generated by Django 3.2.23 on 2024-02-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0024_remove_producto_pertenecarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='perteneceCarrito',
            field=models.BooleanField(default=False),
        ),
    ]
