# Generated by Django 3.2.23 on 2024-02-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0026_remove_producto_pertenececarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='perteneceCarrito',
            field=models.BooleanField(default=False),
        ),
    ]
