# Generated by Django 3.2.23 on 2024-02-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0027_carrito_pertenececarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='perteneceCarrito',
        ),
    ]
