# Generated by Django 3.2.23 on 2024-02-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0028_remove_carrito_pertenececarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(to='producto_app.Producto'),
        ),
    ]
