# Generated by Django 3.2.23 on 2024-03-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0031_auto_20240223_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='perteneceCarrito',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto_app.producto'),
        ),
    ]
