# Generated by Django 3.2.23 on 2024-04-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0033_auto_20240303_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='cantidad',
        ),
    ]
