# Generated by Django 3.2.23 on 2024-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0034_remove_itemcarrito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
