# Generated by Django 3.2.23 on 2024-04-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0035_producto_isselected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='isSelected',
        ),
    ]
