# Generated by Django 3.2.23 on 2024-05-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_imagenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagenU',
            field=models.ImageField(upload_to='User/'),
        ),
    ]
