# Generated by Django 5.0 on 2023-12-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagenU',
            field=models.ImageField(default='IMG-20211017-WA0054.jpg', upload_to='User/'),
        ),
    ]
