# Generated by Django 5.0 on 2023-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_imagenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagenU',
            field=models.ImageField(default='user default.png', upload_to='User/'),
        ),
    ]
