# Generated by Django 3.2.23 on 2024-05-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_imagenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagenU',
            field=models.ImageField(null=True, upload_to='User/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
