# Generated by Django 5.0 on 2024-01-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_imagenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagenU',
        ),
    ]
