# Generated by Django 3.2.23 on 2024-05-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20240516_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagenU',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
