# Generated by Django 5.0.6 on 2024-06-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_user_imagenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagenU',
            field=models.ImageField(blank=True, null=True, upload_to='User/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
