# Generated by Django 5.0.6 on 2024-07-02 06:26

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagenC', models.ImageField(upload_to='categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Entidad/')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('descripcion', models.TextField()),
                ('paginaOficial', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagenP', models.ImageField(upload_to='Productos/')),
                ('modelo_3d', models.FileField(upload_to='modelos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])])),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('largo', models.FloatField()),
                ('unidadM', models.CharField(choices=[('in', 'Pulgadas'), ('m', 'Metros'), ('cm', 'Centímetros')], default='m', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.categoria')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicios.entidad')),
            ],
        ),
    ]
